version: '3.7'

volumes:
  data-postgres:

services:

  ## App server connects to the database and provides an API for frontend
  web:
    image: basil_web:dev # name:tag 
    # https://docs.docker.com/compose/django/
    build: 
      context: web/.      
      args:
        SERVICE_ENVIRONMENT: local # local, dev, stage, prod
    volumes:
      - ./web:/code
    # depends_on:
    #   - db
    ports:
      - 8000:8000 # host:docker
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: basil.settings.local
      DJANGO_DEBUG: 'true'
      # database parameters
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db-postgres

  ## Primary data store for application data
  db:
    build: database/.
    restart: always
    expose:
      - 5432
    volumes:
      # Named volume is not necessary for this, can mount to the system
      # See "Where to Store Data" in https://hub.docker.com/_/postgres
      - data-postgres:/var/lib/postgresql/data      
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      # Comment these lines to persist data on the local filesystem.
      # PGDATA: /opt/postgresql/data
