version: '3.3'

volumes:
  data-postgres:

services:

  ## App server connects to the database and provides an API for frontend
  webserver:
    image: basil_webserver:dev # name:tag 
    build: 
      context: ./webserver/.
      dockerfile: Dockerfile-dev
    volumes:
      - ./webserver:/opt/webserver
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      # CONFIG_FILES: 'base.yaml:local_settings.yaml'
      DJANGO__DEBUG: 'true'
      DJANGO__DATABASES__default__DB: ${POSTGRES_DB}
      DJANGO__DATABASES__default__USER: ${POSTGRES_USER}
      DJANGO__DATABASES__default__PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO__DATABASES__default__HOST: db

  ## Primary data store for application data
  db:
    build: postgres/.
    restart: always
    expose:
      - 5432
    volumes:
      # Named volume is not necessary for this, can mount to the system
      # See "Where to Store Data" in https://hub.docker.com/_/postgres
      - data-postgres:/var/lib/postgresql/data      
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      # Comment these lines to persist data on the local filesystem.
      # PGDATA: /opt/postgresql/data
