# Django core settings

# OVERWRITE SETTINGS USING
#
# ENV DJANGO__<name>
# 


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: '*)s9o+=wjhxn1*1+_ssymqh@rrp#ylko6=9&en*5_enblgy)g5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: True

ALLOWED_HOSTS:
  - 

INSTALLED_APPS:
  - 'django.contrib.admin'
  - 'django.contrib.auth'
  - 'django.contrib.contenttypes'
  - 'django.contrib.sessions'
  - 'django.contrib.messages'
  - 'django.contrib.staticfiles'
  - 'modules'


MIDDLEWARE:
  - 'django.middleware.security.SecurityMiddleware'
  - 'django.contrib.sessions.middleware.SessionMiddleware'
  - 'django.middleware.common.CommonMiddleware'
  - 'django.middleware.csrf.CsrfViewMiddleware'
  - 'django.contrib.auth.middleware.AuthenticationMiddleware'
  - 'django.contrib.messages.middleware.MessageMiddleware'
  - 'django.middleware.clickjacking.XFrameOptionsMiddleware'


ROOT_URLCONF: 'app.urls'

TEMPLATES:
  -
    BACKEND: 'django.template.backends.django.DjangoTemplates'
    APP_DIRS: True
    OPTIONS:
      context_processors:
        - 'django.template.context_processors.debug'
        - 'django.template.context_processors.request'
        - 'django.contrib.auth.context_processors.auth'
        - 'django.contrib.messages.context_processors.messages'


WSGI_APPLICATION: 'app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: stuffdb
    USER: basil
    PASSWORD: EJ60FsNzLrijzwO1rCw
    HOST: postgres
    PORT: 5432


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS:
  -
    NAME: 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
  -
    NAME: 'django.contrib.auth.password_validation.MinimumLengthValidator'
  - 
    NAME: 'django.contrib.auth.password_validation.CommonPasswordValidator'
  - 
    NAME: 'django.contrib.auth.password_validation.NumericPasswordValidator'

LANGUAGE_CODE: 'en-us'

TIME_ZONE: 'UTC'

USE_I18N: True

USE_L10N: True 

USE_TZ: True 

STATIC_URL: '/static/'





