# Generated by Django 3.0.4 on 2020-03-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_create_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='links.Link')),
                ('tag', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='links.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(
                through='links.LinkTag', to='links.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='links',
            field=models.ManyToManyField(
                through='links.LinkTag', to='links.Link'),
        ),
    ]
